version: "2.4"
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - node.name=elas
      - discovery.type=single-node
      - ES_JAVA_OPTS="Xms512m -XMx512m"
      - ELASTIC_PASSWORD="abcdef"
      - KIBANA_SYSTEM_PASSWORD="security"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - certs:/usr/share/elasticsearch/config/certs

  kibana:
    depend:
      - elasticsearch
    image: kibana:8.6.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsear:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSERACH_PASSWORD="abcdef" 
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data

networks:
  elk:

volumes:
  certs: